name: Python App CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Critical Code Checks
        run: |
          pip install flake8
          flake8 app --select=E9,F63,F7,F82 --exit-zero
      
      - name: Test Docker Build
        timeout-minutes: 5
        run: |
          docker build -t kyc-app .
          docker run -d -p 8501:8501 --name test-app kyc-app
          
          # Wait for Streamlit to start (retry for 30 seconds)
          for i in {1..30}; do
            if curl -sSf http://localhost:8501/_stcore/health >/dev/null; then
              echo "Streamlit is running!"
              break
            fi
            sleep 1
          done
          
          # Final verification
          curl -f http://localhost:8501/_stcore/health || exit 1
          docker stop test-app
